#!/bin/sh
# ports/toolchain/install.sh SYSROOT
#
# Installs the Kestrel user-space toolchain wrappers into SYSROOT/bin:
#
#   musl-g++              C++ for Kestrel: the host g++ with musl's C library
#   kestrel-pkg-config    pkg-config against SYSROOT, static link flags
#   kestrel.cmake         CMake toolchain file using the two above
#
# There is no C++ standard library built for musl on the build host, and none
# can be downloaded, so musl-g++ gives C++ programs only what the language
# runtime needs: the host's libstdc++ *headers* for header-only parts
# (<utility>, <algorithm>, <new>, <typeinfo>, ...) and the host's libsupc++
# (operator new/delete, RTTI, dynamic_cast, static-init guards, pure virtual
# handling). Programs that need the compiled parts of libstdc++ (iostreams,
# std::string, <regex>, threads) do not link. libsupc++ was built against
# glibc; the three glibc-only symbols it references are provided by
# libsupcxx-compat.c. Exceptions cannot be thrown (no unwinder support).
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
mkdir -p "$1/bin" "$1/lib"
SYSROOT=$(cd "$1" && pwd)

SPECS=$(musl-gcc -print-file-name=musl-gcc.specs 2>/dev/null || true)
[ -f "$SPECS" ] || SPECS=$(sed -n 's/.*-specs "\([^"]*\)".*/\1/p' "$(command -v musl-gcc)")
[ -f "$SPECS" ] || { echo "toolchain: cannot find musl-gcc.specs"; exit 1; }
V=$(g++ -dumpversion | cut -d. -f1)
CXXINC=/usr/include/c++/$V
CXXARCH=$(g++ -print-multiarch 2>/dev/null || echo x86_64-linux-gnu)
CXXINC_ARCH=/usr/include/$CXXARCH/c++/$V
[ -d "$CXXINC" ] && [ -d "$CXXINC_ARCH" ] || { echo "toolchain: no libstdc++ headers for g++ $V"; exit 1; }

musl-gcc -O2 -fPIE -c "$HERE/libsupcxx-compat.c" -o "$SYSROOT/lib/libsupcxx-compat.o"
ar rcs "$SYSROOT/lib/libsupcxx-compat.a" "$SYSROOT/lib/libsupcxx-compat.o"
rm -f "$SYSROOT/lib/libsupcxx-compat.o"

cat > "$SYSROOT/bin/musl-g++" <<EOF
#!/bin/sh
# Generated by ports/toolchain/install.sh: g++ for Kestrel (musl, libsupc++).
link=1
for a in "\$@"; do
    case "\$a" in -c|-S|-E|-M|-MM) link=;; esac
done
if [ -n "\$link" ]; then
    exec g++ -specs "$SPECS" -nostdinc++ -nostdlib++ '-D__GLIBC_PREREQ(a,b)=0' \\
        -isystem "$CXXINC" -isystem "$CXXINC_ARCH" "\$@" \\
        -L"$SYSROOT/lib" -lsupc++ -lsupcxx-compat
else
    exec g++ -specs "$SPECS" -nostdinc++ '-D__GLIBC_PREREQ(a,b)=0' \\
        -isystem "$CXXINC" -isystem "$CXXINC_ARCH" "\$@"
fi
EOF
chmod +x "$SYSROOT/bin/musl-g++"

cat > "$SYSROOT/bin/kestrel-pkg-config" <<EOF
#!/bin/sh
# Generated by ports/toolchain/install.sh: pkg-config for the Kestrel sysroot.
PKG_CONFIG_PATH= PKG_CONFIG_LIBDIR="$SYSROOT/lib/pkgconfig:$SYSROOT/share/pkgconfig" \\
    exec pkg-config --static "\$@"
EOF
chmod +x "$SYSROOT/bin/kestrel-pkg-config"

cat > "$SYSROOT/bin/kestrel.cmake" <<EOF
# Generated by ports/toolchain/install.sh: CMake toolchain for Kestrel.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER musl-gcc)
set(CMAKE_CXX_COMPILER "$SYSROOT/bin/musl-g++")
set(PKG_CONFIG_EXECUTABLE "$SYSROOT/bin/kestrel-pkg-config")
set(CMAKE_FIND_ROOT_PATH "$SYSROOT")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_C_FLAGS_INIT "-fPIE -DKESTREL_OS")
set(CMAKE_CXX_FLAGS_INIT "-fPIE -DKESTREL_OS")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static-pie")
EOF
echo "toolchain: musl-g++, kestrel-pkg-config, kestrel.cmake in $SYSROOT/bin"
