#!/usr/bin/env python3
"""
tools/bdf2c.py -- convert a fixed-width BDF bitmap font into a C source file
usable by drivers/font.c (struct font).

    python3 tools/bdf2c.py third_party/spleen/spleen-8x16.bdf font_8x16 > drivers/font_8x16.c

Only printable ASCII (0x20-0x7E) is emitted. Each glyph row is stored MSB
first in ceil(width/8) bytes. Any monospace BDF (Spleen, Terminus, Unifont...)
works, so swapping the UI typeface is a one-line Makefile change.
"""
import sys

FIRST, LAST = 0x20, 0x7E


def parse_bdf(path):
    fbb = None
    glyphs = {}
    with open(path, encoding="latin-1") as f:
        lines = iter(f.read().splitlines())
    for line in lines:
        if line.startswith("FONTBOUNDINGBOX"):
            w, h, xo, yo = map(int, line.split()[1:5])
            fbb = (w, h, xo, yo)
        elif line.startswith("STARTCHAR"):
            enc, bbx, rows = None, None, []
            for line in lines:
                if line.startswith("ENCODING"):
                    enc = int(line.split()[1])
                elif line.startswith("BBX"):
                    bbx = tuple(map(int, line.split()[1:5]))
                elif line.startswith("BITMAP"):
                    for line in lines:
                        if line.startswith("ENDCHAR"):
                            break
                        rows.append(line.strip())
                    break
            if enc is not None and FIRST <= enc <= LAST:
                glyphs[enc] = (bbx, rows)
    return fbb, glyphs


def render(fbb, bbx, rows):
    W, H, fxo, fyo = fbb
    bw, bh, bxo, byo = bbx
    grid = [[0] * W for _ in range(H)]
    # top row of glyph box, measured from the top of the font box
    top = (H + fyo) - (bh + byo)
    left = bxo - fxo
    for r, hexrow in enumerate(rows):
        bits = int(hexrow, 16)
        nbits = len(hexrow) * 4
        for c in range(bw):
            if bits & (1 << (nbits - 1 - c)):
                y, x = top + r, left + c
                if 0 <= y < H and 0 <= x < W:
                    grid[y][x] = 1
    return grid


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    path, name = sys.argv[1], sys.argv[2]
    fbb, glyphs = parse_bdf(path)
    W, H = fbb[0], fbb[1]
    bpr = (W + 7) // 8
    out = []
    out.append(f"/* Generated by tools/bdf2c.py from {path.split('/')[-1]} -- do not edit. */")
    out.append('#include <kernel/font.h>\n')
    out.append(f"static const uint8_t {name}_data[{LAST - FIRST + 1} * {H} * {bpr}] = {{")
    for code in range(FIRST, LAST + 1):
        if code in glyphs:
            grid = render(fbb, *glyphs[code])
        else:
            grid = [[0] * W for _ in range(H)]
        vals = []
        for row in grid:
            v = 0
            for x, bit in enumerate(row):
                if bit:
                    v |= 1 << (bpr * 8 - 1 - x)
            for b in range(bpr):
                vals.append((v >> (8 * (bpr - 1 - b))) & 0xFF)
        ch = chr(code)
        label = ch if ch not in "\\*/" else "0x%02X" % code
        out.append(f"    /* '{label}' */ " + ", ".join(f"0x{v:02X}" for v in vals) + ",")
    out.append("};\n")
    out.append(f"const struct font {name} = {{")
    out.append(f"    .width = {W}, .height = {H}, .bytes_per_row = {bpr},")
    out.append(f"    .first = 0x{FIRST:02X}, .last = 0x{LAST:02X}, .data = {name}_data,")
    out.append("};")
    print("\n".join(out))


if __name__ == "__main__":
    main()
