#!/usr/bin/env python3
"""tools/ksyms.py NM_OUTPUT OUT.c -- kernel symbol table for crash backtraces.

Reads `nm -n` output of a first link of the kernel and writes the text
(function) symbols as sorted C arrays: ksym_addr[], ksym_off[] (offsets
into ksym_names), ksym_count. The table lives in .rodata, which the linker
script places after .text, so linking it in does not move any function:
the addresses of the first link stay valid in the final kernel."""
import sys

syms = []
for line in open(sys.argv[1]):
    parts = line.split()
    if len(parts) != 3 or parts[1] not in "Tt":
        continue
    syms.append((int(parts[0], 16), parts[2]))
syms.sort()
names, offs, off = [], [], 0
for _, n in syms:
    offs.append(off)
    names.append(n)
    off += len(n) + 1
with open(sys.argv[2], "w") as f:
    f.write("/* Generated by tools/ksyms.py -- do not edit. */\n#include <stdint.h>\n")
    f.write("const unsigned ksym_count = %d;\n" % len(syms))
    f.write("const uint64_t ksym_addr[] = {\n%s\n};\n" % ",\n".join("    0x%x" % a for a, _ in syms) if syms else "const uint64_t ksym_addr[1];\n")
    f.write("const uint32_t ksym_off[] = {\n%s\n};\n" % ",\n".join("    %d" % o for o in offs) if syms else "const uint32_t ksym_off[1];\n")
    blob = "".join(n + "\\0" for n in names)
    f.write('const char ksym_names[] = "%s";\n' % blob)
