#!/usr/bin/env python3
"""
tools/sheet2font.py -- turn a 16 x 16 glyph sheet image into the C array
`unsigned char kestrel_font[256][16]` (8 x 16 pixels, one byte per row,
bit 7 = leftmost pixel).

    python3 tools/sheet2font.py sheet.png drivers/kestrel_font.c [--preview out.png]

The sheet must hold 256 glyphs in a 16 x 16 grid (code point = row * 16 +
column), light glyphs on a dark background. Any cell size works:

  * an exact 128 x 256 sheet (8 x 16 cells) converts losslessly;
  * a larger or scaled sheet (e.g. 240 x 368 = 15 x 23 cells) is resampled:
    each cell is cropped to its ink bounding box across the whole font
    (so baselines stay aligned), area-averaged down to 8 x 16 and
    thresholded. JPEG noise is removed by the threshold.

Requires Pillow.
"""
import sys
from PIL import Image

W, H = 8, 16


def main():
    argv = sys.argv[1:]
    preview = None
    if "--preview" in argv:
        i = argv.index("--preview")
        preview = argv[i + 1]
        del argv[i:i + 2]
    if len(argv) != 2:
        sys.exit(__doc__)
    src, dst = argv

    img = Image.open(src).convert("L")
    cw, ch = img.size[0] / 16.0, img.size[1] / 16.0
    exact = (cw, ch) == (W, H)
    px = img.load()

    # Common ink box across all cells keeps every glyph on the same baseline.
    x0, y0, x1, y1 = cw, ch, 0, 0
    if not exact:
        for code in range(256):
            cx, cy = (code % 16) * cw, (code // 16) * ch
            for y in range(int(ch)):
                for x in range(int(cw)):
                    if px[int(cx + x), int(cy + y)] > 128:
                        x0, y0 = min(x0, x), min(y0, y)
                        x1, y1 = max(x1, x + 1), max(y1, y + 1)
        # pad the box to the 1:2 cell aspect with a 1-pixel margin
        x0, y0 = max(0, x0 - 1), max(0, y0 - 1)
        x1, y1 = min(int(cw), x1 + 1), min(int(ch), y1 + 1)

    font = []
    for code in range(256):
        cx, cy = (code % 16) * cw, (code // 16) * ch
        if exact:
            cell = img.crop((int(cx), int(cy), int(cx) + W, int(cy) + H))
        else:
            cell = img.crop((int(cx + x0), int(cy + y0), int(cx + x1), int(cy + y1)))
            cell = cell.resize((W, H), Image.BOX)
        cp = cell.load()
        rows = []
        for y in range(H):
            v = 0
            for x in range(W):
                if cp[x, y] > (128 if exact else 96):
                    v |= 0x80 >> x
            rows.append(v)
        font.append(rows)

    with open(dst, "w") as f:
        f.write("/* Generated by tools/sheet2font.py from %s -- 256 glyphs, 8x16, MSB = left. */\n"
                % src.split("/")[-1])
        f.write("#include <kernel/kestrel_font.h>\n\n")
        f.write("unsigned char kestrel_font[256][16] = {\n")
        for code, rows in enumerate(font):
            label = chr(code) if 0x20 < code < 0x7F and chr(code) not in "\\*/" else ""
            f.write("    /* 0x%02X %-1s */ { %s },\n" % (code, label, ", ".join("0x%02X" % r for r in rows)))
        f.write("};\n")

    if preview:
        out = Image.new("L", (16 * W * 4, 16 * H * 4), 0)
        op = out.load()
        for code, rows in enumerate(font):
            ox, oy = (code % 16) * W * 4, (code // 16) * H * 4
            for y, r in enumerate(rows):
                for x in range(W):
                    if r & (0x80 >> x):
                        for dy in range(4):
                            for dx in range(4):
                                op[ox + x * 4 + dx, oy + y * 4 + dy] = 255
        out.save(preview)
    print("%s: %d glyphs written (%s)" % (dst, len(font), "exact" if exact else "resampled from %.0fx%.0f cells" % (cw, ch)))


if __name__ == "__main__":
    main()
