/* include/kernel/font.h -- monospace bitmap fonts (generated by tools/bdf2c.py) */
#ifndef KESTREL_FONT_H
#define KESTREL_FONT_H

#include <stdint.h>

struct font {
    uint8_t width, height;      /* glyph cell in pixels                 */
    uint8_t bytes_per_row;      /* ceil(width / 8), MSB = leftmost pixel */
    uint8_t first, last;        /* encoded character range              */
    const uint8_t *data;        /* (last-first+1) * height * bytes_per_row */
};

/* Spleen by Frederic Cambus (BSD-2-Clause), see third_party/spleen/LICENSE */
extern const struct font font_8x16;     /* kernel console: 128 x 48 cells   */
extern const struct font font_12x24;    /* boot manager:    85 x 32 cells   */

#endif
